### ISSUE TITLE
Endpoint para recomendar productos basados en las compras previas del cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g2_sf#12]
**Endpoint para recomendar productos basados en las compras previas del cliente:**

* **Requerimiento:** Crear un endpoint que recomiende productos al cliente basándose en sus compras anteriores.
* **Funcionalidad:**
  * `GET /productos/recomendaciones/{clienteId}` devuelve una lista de productos recomendados para un cliente específico.
* **Detalle:** Utiliza algoritmos de recomendación para sugerir productos que otros clientes con compras similares han adquirido.

**Comment by SILVIAGONZALEZ1** [comment]
### Descripción de la Solicitud de Extracción

Esta solicitud de extracción incluye la implementación del endpoint para recomendar productos basados en las compras anteriores de un cliente específico.

#### Funcionalidad Implementada
- **GET `/productos/recomendaciones/{clienteId}`**: Retorna una lista de productos recomendados para un cliente específico, utilizando algoritmos de recomendación basados en compras similares de otros clientes.

#### Cambios Realizados
- Se crearon nuevos componentes para implementar la funcionalidad de recomendación de productos:
  - `CompraController`: Controlador para manejar las peticiones relacionadas con recomendaciones de productos.
  - `CompraService`: Servicio que contiene la lógica de negocio para generar recomendaciones basadas en compras anteriores.
  - `CompraServiceImplJpa`: Implementación concreta del servicio de recomendación.
  - `CompraRepository`: Repositorio para acceder a los datos necesarios para calcular las recomendaciones.
  - `Compra`: Nueva Entidad 
   
#### Capturas de Pantalla de las Operaciones
- *GET `/productos/recomendaciones/{clienteId}`*:
 http://localhost:8080/productos/recomendaciones/10
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/22be0d23-7f40-462a-834d-b20c1e82879b)
