### ISSUE TITLE
Persistencia de la entidad Cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g2_sf#15]
#### Requisitos

1. Crear el archivo `ClienteRepository`.
2. Crear el archivo `IClienteService`.
3. Crear el archivo `ClienteServiceImpl`.
4. Crear el archivo `ClienteController`.

#### Métodos en `IClienteService`

    import java.util.List;
    
    public interface IClienteService {
        List<Cliente> getAll();
        Cliente getById(Long id);
        Cliente save(Cliente cliente);
        void delete(Long id);
        boolean exists(Long id);
    }

#### Endpoints en `ClienteController`

* `GET /api/clientes` - Obtener todos los clientes.
* `GET /api/clientes/{id}` - Obtener un cliente por ID.
* `POST /api/clientes` - Crear un nuevo cliente.
* `PUT /api/clientes/{id}` - Actualizar un cliente existente.
* `DELETE /api/clientes/{id}` - Eliminar un cliente por ID.

#### Instrucciones adicionales

* Adjuntar capturas de todas las llamadas a los métodos a través de PostMan en el pull request.

**Comment by SILVIAGONZALEZ1** [comment]
# Descripción de la Solicitud de Extracción

Esta solicitud de extracción incluye la implementación de las siguientes operaciones para la entidad `cliente`:

1. **GET**: Obtener todos los clientes.
2. **GET**: Obtener un cliente específico.
3. **POST**: Crear un nuevo cliente.
4. **PUT**: Actualizar un cliente existente.
5. **DELETE**: Eliminar un cliente específico.

## Capturas de Pantalla de las Operaciones

### GET `http://localhost:8080/api/v1/cliente` 
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/f2cb89b0-eac0-4c7a-bb87-998936e05d66)

### GET `http://localhost:8080/api/v1/cliente/25` 
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/27f64d36-6645-4f02-8a3f-1e7c10ab886d)

### POST `http://localhost:8080/api/v1/cliente`
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/fbc82d74-d508-4756-bc79-7195b7932d1a)

### PUT `http://localhost:8080/api/v1/cliente/25`
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/f57f3ce3-3ec5-4f32-a8de-be1b519d5f18)

### DELETE `http://localhost:8080/api/v1/cliente/1`
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/f7005bf9-bdc1-4a11-ac6a-5fba4a2550f1)
![image](https://github.com/ahumadamob/2024_gc_p3_g2_sf/assets/105380047/4f0fb1d3-97ad-491d-847a-bad8cd4f49ff)
